### ISSUE TITLE
error starting comfyui with Photographypromptnode and artistpromptnode

### ISSUE THREAD

**Issue by Autantpourmoi** [dagthomas/comfyui_dagthomas#14]
hello facing 2 errors with your nodes :
[ERROR] An error occurred while retrieving information for the 'ArtistPromptNode' node.
Traceback (most recent call last):
  File "/home/luc/ComfyUI/server.py", line 447, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 424, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/comfyui_dagthomas/sdxl_utility.py", line 1198, in INPUT_TYPES
    data = json.load(f)
           ^^^^^^^^^^^^
  File "/home/luc/.pyenv/versions/3.12.4/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/home/luc/.pyenv/versions/3.12.4/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/.pyenv/versions/3.12.4/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/.pyenv/versions/3.12.4/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[ERROR] An error occurred while retrieving information for the 'PhotographyPromptNode' node.
Traceback (most recent call last):
  File "/home/luc/ComfyUI/server.py", line 447, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/home/luc/ComfyUI/server.py", line 424, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/ComfyUI/custom_nodes/comfyui_dagthomas/sdxl_utility.py", line 1198, in INPUT_TYPES
    data = json.load(f)
           ^^^^^^^^^^^^
  File "/home/luc/.pyenv/versions/3.12.4/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/home/luc/.pyenv/versions/3.12.4/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/.pyenv/versions/3.12.4/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luc/.pyenv/versions/3.12.4/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dagthomas** [comment]
Possible Causes:
a) Empty JSON files
b) Corrupted JSON files
c) Incorrect file paths
d) Permission issues

Can you try updating the node, and maybe starting CMD with higher permissions before you run comfyui to see if that has solved it?

**Comment by Autantpourmoi** [comment]
> Possible Causes: a) Empty JSON files b) Corrupted JSON files c) Incorrect file paths d) Permission issues
> 
> Can you try updating the node, and maybe starting CMD with higher permissions before you run comfyui to see if that has solved it?

Update did it , no more error messages
